### ISSUE TITLE
Need two loader in one component. Is it possible?

### ISSUE THREAD

**Issue by ycpatel813** [Durgaprasad-Budhwani/react-native-busy-indicator#9] opened 2017-02-07 09:09 UTC
Hello, 
I have login scene and i am using react-native-busy-indicator and it works fine for me. But for forget password I have created modal. can i use both loader differently?

Thank you.

**Comment by RealOrangeOne** [comment] 2017-02-07 09:14
You can't no. but you shouldnt need to. You can control the content when you load it, so just render the component at as close to the top level as you can, then call the event that shows it with whatever text you want. You can call it in as many different places as you want, so there's no real reason to need 2

**Comment by ycpatel813** [comment] 2017-02-07 09:26
<View style={styles.container}>
                       <Modal
                                // Forget Password code here
                              <BusyIndicator/>
                       </Modal>

                      // Login code here
                      <BusyIndicator/>
            </View>

How can i achieve in this code. can you help me?

Thank you.

**Comment by RealOrangeOne** [comment] 2017-02-07 09:52
I dont see a reason you'd want to show the spinner inside the modal. you'd want it over the whole page. You'd only have the lower one, and just trigger it in both cases with different text. it'll always fill out the screen when you show it

**Comment by ycpatel813** [comment] 2017-02-07 11:32
When i use only lower BusyIndicator it is hide behind my modal. so i need two busy loader.

**Comment by RealOrangeOne** [comment] 2017-02-07 12:54
You dont need 2, you just need to render the BusyIndicator higher up in your component stack. The best thing to do it just always render it right at the top level, in index.js or something even. Then call it lower down. It should then show over your modal.

**Comment by RealOrangeOne** [comment] 2017-03-19 10:13
Closing. Issue caused by outside library

**Closed as completed by RealOrangeOne** 2017-03-19 10:13 UTC
Labels: question
