### ISSUE TITLE
Get erro

### ISSUE THREAD

**Issue by orange2003** [Durgaprasad-Budhwani/react-native-busy-indicator#1] opened 2016-02-25 08:27 UTC
I get this error from my project  

Unable to resolve module Subscribable from /Users/gaofei/Documents/reactMiaoMiao/node_modules/react-native-busy-indicator/index.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/Subscribable and its parent directories

ps i use react native 0.2.0

**Comment by elaygl** [comment] 2016-03-08 16:23
+1

**Comment by tal952** [comment] 2016-03-08 16:38
+1

**Comment by varqasim** [comment] 2016-03-24 11:01
You will probably need to install Subscribable into your node_modules, but I'm not sure if you need to install that in your computers root directory as it shows. Here is the package if you're interested https://www.npmjs.com/package/subscribable

**Comment by qpowell** [comment] 2016-03-25 15:46
I had this same issue. Doing `npm install subscribable --save` and changing the line in index.js to `import Subscribable from 'subscribable';` (note the lowercase s instead of Subscribable) worked for me.

Unfortunately, after I did that, it was unable to find EventEmitter as well. 

@Durgaprasad-Budhwani @qasimalbaqali can either of you clarify which EventEmitter this component uses for it's dependency? Is it this one: https://www.npmjs.com/package/wolfy87-eventemitter ?

**Comment by DennisMG** [comment] 2016-04-13 18:06
I'm also facing this issue, does anyone have a fix?

**Comment by jcai** [comment] 2016-04-16 09:23
![image](https://cloud.githubusercontent.com/assets/6152/14580182/ae33a14e-03f7-11e6-8f10-1b1da10fc899.png)

**Comment by RealOrangeOne** [comment] 2016-05-07 20:05
Submitted a PR that fixes a load of issues, 1 of which is this. See #2

**Comment by karthickvkumar** [comment] 2016-05-19 05:10
Great work @RealOrangeOne! 
@Durgaprasad-Budhwani plz find some time to merge that PR

**Comment by RealOrangeOne** [comment] 2016-06-15 14:57
@orange2003 PR merged, close issue?

**Comment by teyou** [comment] 2016-07-09 10:52
and bump npm version?

**Comment by RealOrangeOne** [comment] 2016-07-09 21:40
Missing the bump to npm, but the issue is solved. So I think the issue can be closed

**Comment by teyou** [comment] 2016-07-10 04:04
yeah. pls bump :)

**Comment by RealOrangeOne** [comment] 2016-07-11 13:30
Just pushed a new version, contains these fixes, and some cleanup! Update to `react-native-busy-indicator@1.0.7`!

**Closed as completed by RealOrangeOne** 2016-07-11 13:30 UTC
Labels: bug
